# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcHemi_cpp <- function(coordsI, coordsJ, ls_indexK, n_num, value, n, i_pos, j_pos, angle_pos, penaltyNA, sd_data, p, symetrie) {
    .Call('MRIaggr_calcHemi_cpp', PACKAGE = 'MRIaggr', coordsI, coordsJ, ls_indexK, n_num, value, n, i_pos, j_pos, angle_pos, penaltyNA, sd_data, p, symetrie)
}

calcContro_cpp <- function(contrast, coords_px, index_k, index_k_contro, d_lim, lambda, param_ref, var_ref, type_moy, type_med, type_NN, trace) {
    .Call('MRIaggr_calcContro_cpp', PACKAGE = 'MRIaggr', contrast, coords_px, index_k, index_k_contro, d_lim, lambda, param_ref, var_ref, type_moy, type_med, type_NN, trace)
}

filtrage2D_cpp <- function(M_data, M_operateur, index_data, w_contrast, na_rm) {
    .Call('MRIaggr_filtrage2D_cpp', PACKAGE = 'MRIaggr', M_data, M_operateur, index_data, w_contrast, na_rm)
}

filtrage3D_cpp <- function(Vec_data, p_data, Vec_operateur, p_operateur, index_data, w_contrast, na_rm) {
    .Call('MRIaggr_filtrage3D_cpp', PACKAGE = 'MRIaggr', Vec_data, p_data, Vec_operateur, p_operateur, index_data, w_contrast, na_rm)
}

filtrage2Dmed_cpp <- function(M_data, M_operateur, index_data, na_rm) {
    .Call('MRIaggr_filtrage2Dmed_cpp', PACKAGE = 'MRIaggr', M_data, M_operateur, index_data, na_rm)
}

filtrage3Dmed_cpp <- function(Vec_data, p_data, Vec_operateur, p_operateur, index_data, na_rm) {
    .Call('MRIaggr_filtrage3Dmed_cpp', PACKAGE = 'MRIaggr', Vec_data, p_data, Vec_operateur, p_operateur, index_data, na_rm)
}

calcGroupsCoords_cpp <- function(coords_NNA, index_NNA, Neighborhood, coords_max, max_groups, trace) {
    .Call('MRIaggr_calcGroupsCoords_cpp', PACKAGE = 'MRIaggr', coords_NNA, index_NNA, Neighborhood, coords_max, max_groups, trace)
}

calcGroupsW_cpp <- function(W, subset, max_groups) {
    .Call('MRIaggr_calcGroupsW_cpp', PACKAGE = 'MRIaggr', W, subset, max_groups)
}

calcRadius_cpp <- function(coords, sample, threshold, subset_bary, trace) {
    .Call('MRIaggr_calcRadius_cpp', PACKAGE = 'MRIaggr', coords, sample, threshold, subset_bary, trace)
}

